### ISSUE TITLE
chore: Delete `components` files

### ISSUE THREAD

**Issue by delisma** [canada-ca/design-system#122]
@jmealing do we have a rationale for this folder to exist in English but not in French?

**Comment by jmealing** [comment]
That was content Miguel and I had been working on a few years ago for a new design system content template, they would load into pages like this, for example https://design.canada.ca/components/tables-alpha-demo.html

These demos and pages they're for should be marked to move to the experimental repo

**Comment by delisma** [comment]
That is a great idea! I'll marked them for migration instead then.

**Comment by delisma** [comment]
Duplicate of #131
