### ISSUE TITLE
New GitHub Pages options

### ISSUE THREAD

**Issue by nschonni** [canada-ca/design-system#126]
FYI, the Jekyll work by @delisma is good, but just wanted to flag that there are now some additional options for GitHub pages announced https://github.blog/2022-08-10-github-pages-now-uses-actions-by-default/

**Comment by delisma** [comment]
I'm looking into re-organizing the design-system and system-conception repo into a single repo that would be deployed on Netlify. The difference in workflow is not huge if GitHub Actions support building individual folders (en, fr) to separate urls (design.canada.ca, conception.canada.ca). It could be explored once the merge is completed.
