### ISSUE TITLE
chore: Delete files in common design patterns

### ISSUE THREAD

**Issue by DDubuc1** [canada-ca/design-system#130]
common-design-patterns/contextual-alerts-component-demo.html
common-design-patterns/contextual-alerts-design-guidelines.html
common-design-patterns/global-header-workshop.html
common-design-patterns/latest-news-2.html
common-design-patterns/page-group-nav.html
common-design-patterns/site-footer-workshop.html

these files have been marked for deletion

**Comment by jmealing** [comment]
I'm actively working on some of these files, others should be moved to experimental. Please don't delete until I've finished reviewing

**Comment by delisma** [comment]
@jmealing Aside from `common-design-patterns/global-header-workshop.html` and `common-design-patterns/site-footer-workshop.html` which could stay in here at the moment, we could move the rest to `gc-proto/experimental`.

Any thoughts?

**Comment by jmealing** [comment]
Seems like the `global-header-workshop` could be deleted. Peter Crane was working on that elsewhere

I've moved the footer work already to experimental

I don't know what latest-news-2.html is

The rest that haven't been taken care of could go to experimental

**Comment by delisma** [comment]
Ok so:
- `common-design-patterns/contextual-alerts-component-demo.html`
- `common-design-patterns/contextual-alerts-design-guidelines.html`-
-  `common-design-patterns/latest-news-2.html`
- `common-design-patterns/page-group-nav.html`
Are moving to `gc-proto/experimental`.

and:
- `common-design-patterns/global-header-workshop.html`
Is in `gc-proto/design-system-proto`

**Comment by jmealing** [comment]
What is the  `gc-proto/design-system-proto`  and what is the difference between moving things there vs the `gc-proto/experimental` like the ILP work ?

**Comment by delisma** [comment]
The `gc-proto/design-system-proto` is a fork of `canada-ca/design-system` and it's the final playground before going live. That's where I want to move our workshops session. While `gc-proto/experiment` or `jmealing/[repo]` will be considered as a personal sandbox where you tinker before you share your work.
