### ISSUE TITLE
chore: Move files in `images` folder to `gc-proto/experimental`

### ISSUE THREAD

**Issue by DDubuc1** [canada-ca/design-system#142]
images/360x203.jpg
images/alert-deutanopia.png
images/alert-spec-en.png
images/alert-tritanopia.png
images/contact-form/feedback-form-thumbnail.png
images/data-picture/cave-high-res.jpg
images/data-picture/cave-low-res.jpg
images/data-picture/parliament-hill-extralarge.jpg
images/data-picture/parliament-hill-large.jpg
images/data-picture/parliament-hill-medium.jpg
images/data-picture/parliament-hill-small.jpg
images/interactive-questions/contextual-validation.png
images/interactive-questions/dropdown-menu-children.png
images/interactive-questions/radio-marital.png
images/interactive-questions/single-item-checklist.png
images/interactive-questions/task-heading.png
images/link-description/link-description-spec-en.png
images/ministerial-page-cropped.jpg
images/social-media/facebook.png
images/social-media/instagram.png
images/social-media/linkedin.png
images/social-media/twitter.png
images/social-media/youtube.png

these files have been flagged to be moved to GC-proto Experimental

GC-proto link : https://github.com/gc-proto/experimental/issues/15

**Comment by jmealing** [comment]
Keep the following, they are being used on the live theme/topic coded layout

images/social-media/facebook.png
images/social-media/instagram.png
images/social-media/linkedin.png
images/social-media/twitter.png
images/social-media/youtube.png

Rest can move to experimental

**Comment by delisma** [comment]
> Keep the following, they are being used on the live theme/topic coded layout
> 
> - images/social-media/facebook.png 
> - images/social-media/instagram.png 
> - images/social-media/linkedin.png 
> - images/social-media/twitter.png 
> - images/social-media/youtube.png
> 
> Rest can move to experimental

Yes! These files weren't flagged to be moved to `gc-proto/experimental`. They were flag to be added to the `gc-proto/systeme-conception`.
