### ISSUE TITLE
chore: Move and add files in `js` folder to `experimental` and `systeme-conception`

### ISSUE THREAD

**Issue by DDubuc1** [canada-ca/design-system#145]
js/checkbox-labels.js
js/demo-toggles.js
js/resize-iframe.js

these files have been marked to be moved to GC-Proto experimental

link to Proto repo : https://github.com/gc-proto/experimental/issues/17

**Comment by delisma** [comment]
Only `js/checkbox-label.js` needs to be moved to `gc-proto/experimental`.
`js/demo-toggle.js` needs to be added to `gc-proto/systeme-conception`.
`js/resize-iframe.js` needs to be added to `gc-proto/systeme-conception`.
