### ISSUE TITLE
Tables pattern - broken example for beta responsive tables

### ISSUE THREAD

**Issue by catalinaperezn** [canada-ca/design-system#168]

**Comment by pcwsmith** [comment]
on https://design.canada.ca/common-design-patterns/tables.html, under How to implement, in the expando for Beta (responsive) data tables, the examples at various screen sizes are giving a 404.



![Image](https://user-images.githubusercontent.com/5454117/187222820-26e1b777-dcbc-4df3-aa72-75d5af6aae10.png)

**Comment by delisma** [comment]
I'll add it to the bug tracker.

**Comment by pcwsmith** [comment]
Oh I thought this was the bug tracker?

**Comment by pcwsmith** [comment]
🙌
