### ISSUE TITLE
[BUG]: Broken links to /styles/colours.html

### ISSUE THREAD

**Issue by DMcDona** [canada-ca/design-system#169]
Hi all, stumbled across some broken links pointing to https://design.canada.ca/styles/colours.html 

I'd report this elsewhere, but the En language toggle on https://conception.canada.ca/styles/couleurs.html is also leading to a 404. 

I'm guessing that [styles/colour](https://github.com/canada-ca/design-system/blob/master/styles/colour.html) used to be styles/colours. 

This also broke external links within the past few days:
https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-information-architecture-specification/mandatory-elements.html "Colours" link from here

Thanks!

(And sorry if this isn't the correct place to submit this / if it isn't related. I assumed design.canada.ca is pulling from this github repo based on the 404 page.)

**Comment by delisma** [comment]
@DMcDona This is the correct place to report it! We are undergoing some maintenance work. We had some duplicate files for colors.html. Seems like we moved the wrong files that we will put back shortly.
