### ISSUE TITLE
Should we use or completely avoid the WET Theme and topics BETA template (last mod 2020) and why?

### ISSUE THREAD

**Issue by MrProulx** [canada-ca/design-system#213]
### Discussed in https://github.com/orgs/canada-ca/discussions/63

<div type='discussions-op-text'>

<sup>Originally posted by **MrProulx** March  3, 2023</sup>
Are there any major concerns in using the TBS Theme and topics **[BETA template](https://design.canada.ca/coded-layout/theme_topic_guidance.html)** (last mod 2020) for a GoC website's landing pages?

Is there a newer (stable) version coming down the pipe? I'm worried that moving to an old/stagnant BETA would give us extra work to update landing pages -- and then later have to migrate everything back because it could be obsolete, or that there would be a better alternative that does not involve a BETA. Or... just status quo. Thoughts?</div>

**Comment by delisma** [comment]
We will be working on making this pattern stable in 2023-2024. Right now the code example in the design system is completely broken and the [correct one to use can be found here](https://wet-boew.github.io/GCWeb/templates/theme-topic/theme-topic-en.html), but the coding documentation is lacking.

**Comment by MrProulx** [comment]
> We will be working on making this pattern stable in 2023-2024. Right now the code example in the design system is completely broken and the [correct one to use can be found here](https://wet-boew.github.io/GCWeb/templates/theme-topic/theme-topic-en.html), but the coding documentation is lacking.

Oh, interesting. We are testing a mock-up landing page 'beta' (the beta version that is in the Canada.ca themes, which you said is broken), with WET12 but the image near the H1 gets tossed at the footer. 

I can have a look at your newer example. I was looking for ways to break the news to my team that we should steer clear of the beta version and stick with stable versions... If you have a final word on that, I would appreciate it lol.

**Comment by MrProulx** [comment]
> We will be working on making this pattern stable in 2023-2024. Right now the code example in the design system is completely broken and the [correct one to use can be found here](https://wet-boew.github.io/GCWeb/templates/theme-topic/theme-topic-en.html), but the coding documentation is lacking.

Possibly add a note on the templates page to mention it's 'broken'

**Comment by MrProulx** [comment]
We decided to follow your recommendations and abandon the beta and stick with stable version of the topic pages for now!
