### ISSUE TITLE
Tabbed Interface: Carousel - request to remove entirely from design system

### ISSUE THREAD

**Issue by MaryBethBaker** [canada-ca/design-system#43]
Evening,

Requesting the removal of the tabbed interface, see duplicate issue posted in the WET-BOEW repository:
https://github.com/wet-boew/wet-boew/issues/8902

Thanks!
Mary Beth

cc @delisma @pcwsmith

**Comment by pcwsmith** [comment]
This can be marked done. We actually updated the documentation to clarify that it is only meant for image or video galleries.
