### ISSUE TITLE
chore: Rename `alerts/alertes`

### ISSUE THREAD

**Issue by DDubuc1** [canada-ca/design-system#70]
alertes-fr-contact.html
alertes-fr-ilp.html
alertes-fr-profil-inst-stable.html
alertes-fr-sit.html
alertes-fr.html

These following files have been marked for deletion from the EN repo. Is there any context we should be aware of before proceeding?

**Comment by delisma** [comment]
Nice job @DDubuc1! There’s a [PR](https://github.com/canada-ca/systeme-conception/pull/42) in the FR repo that creates these files too.
