### ISSUE TITLE
Chore : images / report-fr.png + rest of images in subfolder are marked for deletion

### ISSUE THREAD

**Issue by DDubuc1** [canada-ca/design-system#86]
Hi Folks, 

these files have been marked for deletion. Is there any additional context we should be aware of?

report-fr.png
service-standards-page-fr.jpg
sig-fr.png
site-footer-fr.png
site-search-fr.png
theme-page-fr.jpg

**Comment by delisma** [comment]
@jmealing's commit d4c152bbdacc07d12441c0c92d79da14ad72fbd1 closes this issue.
