### ISSUE TITLE
chore: Move `coded-layout` files to gc-proto/experimental

### ISSUE THREAD

**Issue by DDubuc1** [canada-ca/design-system#92]
Hi Folks, 

These files have been marked for deletion. Is there any additional context we should be aware of?

**coded-layout**
institutional_landing_page_guidance-draft.html 
institutional_landing_page_guidance-minister-horizontal-1.html html  
institutional_landing_page_guidance-minister-horizontal-8.html html 
institutional_landing_page_guidance-minister-horizontal.html 
institutional_landing_page_guidance-minister-no-photos.html 
theme_topic_guidance-draft.html
collapsible-content.html
generic-destination-basic-alert-example.html
sip-apply.html
sip-before.html
sip-contact.html
sip-how-much.html
sip-index-en.html
sip-who.html

thsese files have been marked for deletion

**Comment by delisma** [comment]
Request by @jmealing to move these files with https://github.com/gc-proto/experimental/issues/8
