### ISSUE TITLE
Chore : design-system/jmtesting/ subfolder has been marked for deletion

### ISSUE THREAD

**Issue by DDubuc1** [canada-ca/design-system#96]
Hi Folks, 

These folders have been marked for deletion. Is there any additional context we should be aware of?

**Comment by delisma** [comment]
@jmealing We have 2 choices instead of completely erase this folder:
1. We can create a branch called jmtesting to store all your work
2. We can fork the whole repo to github.com/jmealing/design-system then remove the jmtesting folder in this repo

Thoughts?

**Comment by jmealing** [comment]
I've removed it, no need for a branch because it can't be seen live. It should go in our eventual sandbox
